spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
logging:
  pattern:
    console: "%d --- %msg%n"
  level: error
  file: sell.log


wechat:
  mpAppId: 123AD2Asfasd  #随便写的
  mpAppSecret: 123hkjhkhkh123 #随便写的
  redirectURl: 123123132 #随便写的
  mchId: 12312312312
  mchKey: 123123123123123123
  keyPath: /var/weixin_cert/h5.p12